### ISSUE TITLE
Missing Profile Card BG Blur

### ISSUE THREAD

**Issue by Davoleo** [KorbsStudio/Aurora#2]
There are some issues when you click on the mention to open the profile card of a user
This basically explains the problem:
![image](https://user-images.githubusercontent.com/24458276/78716001-807ee100-791e-11ea-9a50-fafffe7fc50c.png)

The Background is not blurred and text from the card mixes with the text below making the profile card unreadable

**Comment by KorbsStudio** [comment]
I have tried fixing this, I don't know how to sadly.
I'll look back into it later.

**Comment by KorbsStudio** [comment]
Hi there. This is an issue for other themes as well, sadly I still don't know how to fix this for Aurora.

**Comment by alexhora** [comment]
for me it looks fine, unless i am missing the point... 
![2020-05-23_092143](https://user-images.githubusercontent.com/4534959/82724669-fb863600-9cd7-11ea-971d-760b8941ae0d.jpg)

transparency + blur working

**Comment by Davoleo** [comment]
this only happens when you click on a user mention @alexhora

**Comment by KorbsStudio** [comment]
Davoleo is right. I did however manage to add a dark overlay using a `::before` class name.

**Comment by KorbsStudio** [comment]
The backdrop blur still needs to be fixed, sadly this wasn't working with `::before` when opening a profile modal from a mentioned user.

**Comment by alexhora** [comment]
oh indeed how could i've missed that one
bandagedbd looks ok 
![mention_bandagedbd_unbigged](https://user-images.githubusercontent.com/4534959/82803687-44c5b980-9e81-11ea-87cf-ee861f6e34cc.jpg)

transparency bugging in powercord
![mention_powercord_bugged](https://user-images.githubusercontent.com/4534959/82803742-58712000-9e81-11ea-8382-947e2a789233.jpg)
maybe those selectors: 
.theme-dark .mentioned-xhSam7 .mention.interactive:hover, .theme-light .mentioned-xhSam7 .mention.interactive:hover

greetz
