### ISSUE TITLE
media embed visual bug (yt/twitch ok)

### ISSUE THREAD

**Issue by alexhora** [KorbsStudio/Aurora#4]
hello

"tried" to figure what's what in the css but uhmmm NOPE sry ;)
as the title says, a media embed from streamable has a visual bug - yt and twitch ok, i couldn't find another that looked weird (yet)
the fullscreen button is kinda cut off 
lookie->
![unthemed unbugged](https://imgur.com/QI1l8cF.jpg) ![themed bugged](https://imgur.com/F9OHEK3.jpg)
https://imgur.com/a/A5QVKyn

thanks for your effort, this theme is just too nice to let it die 
greets

**Comment by KorbsStudio** [comment]
Should be a easy fix, I'll get to it today.
