### ISSUE TITLE
status linewrap bugged with BandagedBD

### ISSUE THREAD

**Issue by alexhora** [KorbsStudio/Aurora#6]
BandagedBD bugging: 
![status-bugged](https://user-images.githubusercontent.com/4534959/82724882-5d936b00-9cd9-11ea-8aeb-e10c9cd6a757.jpg)

Powercord ok:
![status-unbugged](https://user-images.githubusercontent.com/4534959/82724891-7bf96680-9cd9-11ea-9d65-0d3a9a916717.jpg)

greetz

**Comment by KorbsStudio** [comment]
I'm not sure what's causing the issue for this, I'll have to install BD to find out.
Give me a while.

**Comment by alexhora** [comment]
you = hero ;)
and how quick... 
thx a bunch!
