### ISSUE TITLE
Missing stuff

### ISSUE THREAD

**Issue by ShadowOG69** [KorbsStudio/Aurora#8]
There's missing friend search bar:
[Click me for photo](https://i.gyazo.com/27e78924550b5f40e32200f069ffaee9.png)

There's missing nitro gifting & gif:
[Click me for photo](https://i.gyazo.com/c3d49b279c44ea53bd6152afe550bb53.png)

**Comment by KorbsStudio** [comment]
The search bar in friends in not needed.
You can access it anywhere by pressing "Ctrl/⌘" "K", it's called the **Quicker Switcher**, which you can read more about [here](https://support.discord.com/hc/en-us/articles/115000070311-Quick-Switcher-T-A-Y-N-E-) from Discord's site.

The gift button is a little neaty to me and the GIF button is not needed as it's in the emoji menu.
You can quickly access the GIF menu by pressing "Ctrl/⌘" "G".

So these are not missing, they were removed on purpose.
